name: Project Builds
run-name: ${{ github.actor }} is building project on ${{ github.server_url }}
on:
  push:
    branches:
      - main
env:
  PLATFORM: derecho
jobs:
  build-binaries:
    runs-on: self-hosted
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: echo "This job's status is ${{ job.status }}."

      - name: Show info about `base` environment
        shell: "bash -l {0}"
        run: |
          module load conda
          conda info
          conda config --show-sources
          conda list --show-channel-urls
    
#       - name: Set up `env`
#         shell: "bash -l {0}"
#         run: >
#           conda create -n env
#           c-compiler cxx-compiler
#           python=3.10  wheel pip
      - name: submit job
        shell: "bash -l {0}"
        run: |
           echo $PWD
           module load singularity
           singularity instance start --nv --bind /glade:/glade /glade/cheyenne/scratch/haiyingx/sperr-gnu_cuda_backend_kokkos_Cpp17.sif instance0

           qcmd -q main -l select=1:ncpus=1:mpiprocs=1 -A AHAO0002 -l walltime=0:05:00 -- "date && hostname" 
           singularity instance stop instance0

